### PR TITLE
Fix deleting unused packages

### LINKED ISSUE #172: deleteUnusedPackages.php typo breaks the script
Running `cli/deleteUnusedPackages.php` does not work because of a typo in the loop; the wrong variable is used which results in no unused packages being deleted.

A message is printed that says packages were deleted but it is wrong:
```
Number of deleted packages: 1999
```

The problem is clear from the error message that is printed every iteration:
```
PHP Notice:  Undefined variable: pkgId in /var/www/pakiti3/src/modules/cli/deleteUnusedPackages.php on line 8
```

### PR DESCRIPTION
**Pull request by bluikko**
Simple fix missing letter "s" in loop to make deleting unused packages work.

Fixes #172

### CODE REVIEW

File: src/modules/cli/deleteUnusedPackages.php [hunk 1]
```diff
@@ -5,6 +5,6 @@
 
 $pkgsIds = $pakiti->getManager("PkgsManager")->getUnusedPkgsIds();
 foreach ($pkgsIds as $pkgsId) {
-    $pakiti->getManager("PkgsManager")->deletePkg($pkgId);
+    $pakiti->getManager("PkgsManager")->deletePkg($pkgsId);
```
Comment (bluikko) [inline src/modules/cli/deleteUnusedPackages.php:8]: The other option would be to rename the variable to $pkgId, not sure which is the project's preferred way.
I can create a new PR if it should be $pkgId, obviously it takes about 2 minutes.
